### ISSUE TITLE
Macports can interfere with the AppleTVOS build

### ISSUE THREAD

**Issue by prestonj** [jasonacox/Build-OpenSSL-cURL#1]
Awesome scripts! 

Just pointing out that for me, the AppleTVOS curl build failed due to my macports "ar" program being picked up (it was in my path - you'll see a log message about /opt/local/bin/ar failing in the curl log). A quick cleanup of the path (so that the build uses /usr/bin/ar) fixed the problem.

Perhaps worth putting a little note in the README?

**Comment by jasonacox** [comment]
Thanks prestonj - I'll add this note to the README.
