### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pjbruce** [jasonacox/Build-OpenSSL-cURL#10]
curlrules.h:143:6: '__curl_rule_01__' declared as an array with a negative size

**Comment by pjbruce** [comment]
I have solved the problem. Please refer to http://stackoverflow.com/questions/21681954/using-curl-on-ios-i-am-unable-to-link-with-multiple-architectures-curlchkszeq.

**Comment by jasonacox** [comment]
Thanks pjbruce -  If you get this error, edit the curlbuild.h header file:

```
/* The size of `long', as computed by sizeof. */
// ADD Condition for 64 Bit
#ifdef __LP64__
#define CURL_SIZEOF_LONG 8
#else
#define CURL_SIZEOF_LONG 4
#endif
```

I also found that I needed to treat this section:

```
/* Signed integral data type used for curl_off_t. */
//#define CURL_TYPEOF_CURL_OFF_T long
//ADD Condition for 64 Bit
#define CURL_TYPEOF_CURL_OFF_T int64_t
```

I'll add notes to the README.
