### ISSUE TITLE
It is not support IPV6.

### ISSUE THREAD

**Issue by pjbruce** [jasonacox/Build-OpenSSL-cURL#11]
How can I enable IPV6?

Thanks.

**Comment by jasonacox** [comment]
IPv6 is enabled by default in the build. Make sure you workstation and local router is set up for IPv6 and you should be able to hit an IPv6 site like: https://ipv6.google.com/?gws_rd=ssl

Test:
`$ curl -v https://ipv6.google.com/?gws_rd=ssl
*   Trying 2607:f8b0:4007:808::200e...
* Connected to ipv6.google.com (2607:f8b0:4007:808::200e) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.google.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
> GET /?gws_rd=ssl HTTP/1.1
> Host: ipv6.google.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 05 Sep 2016 17:09:28 GMT
...`

NOTE: If you are trying to specify the IPv6 address, you need to use brackets in the URL, like this:

`https://[2607:f8b0:4007:808::200e]/`
