### ISSUE TITLE
iOS in IPV6.

### ISSUE THREAD

**Issue by pjbruce** [jasonacox/Build-OpenSSL-cURL#12]
1. I finished build the curl.
2. I use Mac Pro to create IPV6 network.
3. I build an app for iOS's device.
4. I use the app to connect a url.
5. Unfortunately, curl failed to connect the url.

What wrong with I?

**Comment by jasonacox** [comment]
What URL are you using?

**Comment by jasonacox** [comment]
It sounds like your local network and ISP does not support IPv6.  Your ISP and DNS servers will need to support IPv6.

You can try running a local web server and hitting the IPv6 local address to see if that works:

1. Run a local web server on your Mac on port 80 (e.g. `sudo apachectl start`).
2. From the same Mac, go into the `cd Build-OpenSSL-cURL/archive/libcurl*`  directory that contains the last build you did along with a Mac binary for `curl` that was built with this script.
3. Run this command:  `curl -i http://[::1]` - This tells curl to GET from the IPv6 localhost port 80.

Here is what I get:

```
$ curl -iv http://[::1]
* Rebuilt URL to: http://[::1]/
*   Trying ::1...
* Connected to ::1 (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: [::1]
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Wed, 07 Sep 2016 22:23:37 GMT
Date: Wed, 07 Sep 2016 22:23:37 GMT
< Server: Apache/2.4.18 (Unix)
Server: Apache/2.4.18 (Unix)
< Content-Location: index.html.en
Content-Location: index.html.en
< Vary: negotiate
Vary: negotiate
< TCN: choice
TCN: choice
< Last-Modified: Mon, 11 Jun 2007 18:53:14 GMT
Last-Modified: Mon, 11 Jun 2007 18:53:14 GMT
< ETag: "2d-432a5e4a73a80"
ETag: "2d-432a5e4a73a80"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Length: 45
Content-Length: 45
< Content-Type: text/html
Content-Type: text/html

< 
<html><body><h1>It works!</h1></body></html>
* Connection #0 to host ::1 left intact
```

**Comment by pjbruce** [comment]
Thanks your response.
Apple ask all iOS APPs to support IPV6 now. I want to use libcurl lib in my app.
Apple allow us create IPV6 network from our MAC and test IPV6.
Please see the link https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1.

I have not succeed to connect url until now. Maybe some configuration is not set.

**Comment by jasonacox** [comment]
@pjbruce - Were you able to get it to work?  

I use the libcurl built by this script in my app, iCurlHTTP, and the latest version was just approved by Apple (https://itunes.apple.com/us/app/icurlhttp/id611943891?ls=1&mt=8).  Hopefully it will work for you as well!
