### ISSUE TITLE
Curl Not building for TV-OS. 

### ISSUE THREAD

**Issue by bhatti-waqas** [jasonacox/Build-OpenSSL-cURL#16]
It shows

Downloading curl-7.50.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8685k  100 8685k    0     0   204k      0  0:00:42  0:00:42 --:--:--  401k
Unpacking curl
Building Mac libraries
Building curl-7.50.1 for x86_64

Then stops. When I look in lib folder. No file is there.

**Comment by jasonacox** [comment]
Look in /tmp and see if you have a curl*.log file.  Look at that to see what broke the build:

tail /tmp/curl*.log

**Comment by jasonacox** [comment]
This made me think of a feature that could be handy for anyone experiencing similar issues.  I added a trap in the build scripts to catch errors and auto-display the log file from the build.  This may help identify the cause of the build failure.
