### ISSUE TITLE
Breaks with openssl 1.1 and Xcode 8

### ISSUE THREAD

**Issue by mickeyl** [jasonacox/Build-OpenSSL-cURL#18]
Thanks for the project. With newer openssl releases (i.e. 1.1.0e) the build fails with
```
ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any idea how to fix this?

**Comment by jasonacox** [comment]
That's correct.  The build scripts in this project only work with the OpenSSL 1.0.1 and 1.0.2 series (current stable version is 1.0.2k) which is the long term support (LTS) version of OpenSSL [support will be provided until 31st December 2019].  The 1.1.0 series is in rapid development (see https://www.openssl.org/policies/releasestrat.html) so I have not invested any time to make this build script work with that series.  

Having said that, if anyone is willing to fork or update the build script to work with the 1.1.0 series, I would welcome the contribution! :-)
