### ISSUE TITLE
How to build custom version?

### ISSUE THREAD

**Issue by qokelate** [jasonacox/Build-OpenSSL-cURL#21]
```
OPENSSL="1.1.0h"
LIBCURL="7.60.0"
NGHTTP2="1.32.0"
```

too many errors, hot to fix?

**Comment by jasonacox** [comment]
what are the errors?

**Comment by jasonacox** [comment]
I have upgraded the build scripts to compile the OpenSSL 1.1.1 series.  Please try using the 1.1.1 series as that is the long term support (LTS) version.
