### ISSUE TITLE
armv7s is not included in libcrypto and libssl builds

### ISSUE THREAD

**Issue by jbfitbit** [jasonacox/Build-OpenSSL-cURL#24]
See https://github.com/jasonacox/Build-OpenSSL-cURL/blob/master/openssl/openssl-build.sh#L200

That script builds in folder `/tmp/${OPENSSL_VERSION}-iOS-armv7s` but that build is not included in the following lipo command:

https://github.com/jasonacox/Build-OpenSSL-cURL/blob/master/openssl/openssl-build.sh#L207

**Comment by jasonacox** [comment]
Good catch - thanks for the PR!
