### ISSUE TITLE
http2 server push how to test ?

### ISSUE THREAD

**Issue by muyushifang07** [jasonacox/Build-OpenSSL-cURL#27]
http2 server push how to test ?

Build-OpenSSL-cURL-master⁩ ▸ ⁨examples⁩ ▸ ⁨iOS Test App⁩ ▸ ⁨include⁩ 
have no nghttp2  files contains .h headers?

**Comment by jasonacox** [comment]
The build.sh script now pushes complied libraries and headers to the "iOS Test App" example (examples/iOS Test App).
