### ISSUE TITLE
Undefined symbols _RTMP_Alloc

### ISSUE THREAD

**Issue by qokelate** [jasonacox/Build-OpenSSL-cURL#29]
library: `libcurl-7.64.1-openssl-1.1.1b-nghttp2-1.37.0`

```
Undefined symbols for architecture x86_64:
  "_RTMP_Alloc", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Close", referenced from:
      _rtmp_disconnect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Connect1", referenced from:
      _rtmp_connect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_ConnectStream", referenced from:
      _rtmp_do in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Free", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
      _rtmp_disconnect in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Init", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Read", referenced from:
      _rtmp_recv in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_SetBufferMS", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_SetupURL", referenced from:
      _rtmp_setup_connection in libcurl.a(libcurl_la-curl_rtmp.o)
  "_RTMP_Write", referenced from:
      _rtmp_send in libcurl.a(libcurl_la-curl_rtmp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

where are the symbols?

**Comment by jasonacox** [comment]
I see this is for the x86_64 arch.  Is this from the build script?  Please pull the latest and try the build again.

**Comment by MarcelKlammer** [comment]
Ran into the same issue.

changed the configure lines to only include http and https:

--disable-shared \
--disable-ftp \
--disable-file \
--disable-ldap \
--disable-dict \
--disable-telnet \
--disable-tftp \
--disable-rtsp \
--disable-pop3 \
--disable-imap \
--disable-smtp \
--disable-gopher \
--disable-ares \
--disable-smb \
--disable-debug \
--disable-cookies \
--disable-manual \
--disable-proxy \
--disable-unix-sockets \
--without-libidn \
--without-libidn2 \
--without-librtmp \
--without-zlib \
--enable-static \
--with-random=/dev/urandom \

**Comment by jasonacox** [comment]
I have not been able to reproduce, even on new MacOS build hosts.  Is this still occurring with latest build script?

**Comment by jasonacox** [comment]
Closing with the new update - please open if it is still an issue.
