### ISSUE TITLE
Compilation failing with curlrules

### ISSUE THREAD

**Issue by aGaneshBanda** [jasonacox/Build-OpenSSL-cURL#3]
Hi, 
Firstly thank you so much for this script. It makes life soo easy. 

I have an issue compiling with the built libs. 
curl/curlrules.h:143:6: '__curl_rule_01__' declared as an array with a negative size

**Comment by aGaneshBanda** [comment]
Issue resolved by removing armv7 and armv7s from compilation. 
Hence the lib built was not compatible with these architectures. Even thou it shows it in xcrun

**Comment by jasonacox** [comment]
Thanks for the feedback.  Interesting!  I'll take a look...

**Comment by jasonacox** [comment]
I haven't been able to reproduce this with the latest version of Xcode and the updated build scripts.  I'm closing this for now but please re-open if you see it occur again.
