### ISSUE TITLE
Suggestion: Include header files with archives

### ISSUE THREAD

**Issue by jbfitb** [jasonacox/Build-OpenSSL-cURL#31]
Currently there are nice `.a` files but no header files. Would be great to have, so I can use the archives without having to clone each repo at that version number to get the headers.

**Comment by jasonacox** [comment]
Thanks!  The `build.sh` script has been updated to archive the openssl and libcurl header files in the `./archive/include` folder.

**Comment by jbfitb** [comment]
whoa you're amazing!
