### ISSUE TITLE
curl/libcurl-build.sh disable-shared

### ISSUE THREAD

**Issue by MarcelKlammer** [jasonacox/Build-OpenSSL-cURL#34]
Shouldn't it read:

./configure --disable-shared

instead of 

./configure -disable-shared

in curl/libcurl-build.sh?

Docs: https://curl.haxx.se/docs/install.html

**Comment by jasonacox** [comment]
Great catch!  Yes.  It has been wrong for a long while.  I think the only reason it still worked and produced static libraries is the `--enable-static` argument that is in there as well (forcing static libraries to be built).  I have updated the `libcurl-build.sh` to use the double dash `--disable-shared` and have successfully tested the build and static libraries.
