### ISSUE TITLE
How could i use this version(1.1.1g) for apple watch along with iOS app ?There was a old project  using  the version 1.0.2d which was also support the Apple watch. So now i want to update the openssl version and i am new to  this so i want to know how could i do it ?

### ISSUE THREAD

**Issue by sunilsingh28011** [jasonacox/Build-OpenSSL-cURL#40]

**Comment by jasonacox** [comment]
Hi @sunilsingh28011, the 1.0.2d version of OpenSSL is end of life and no longer supported for security updates.  I recommend against using that version and adapting the WatchOS project you found to use the long term support 1.1.1 version.  

Note, if you do want to build 1.0.2d, you can still do that using the `-o` option on the build script:
```bash
./build.sh -o 1.0.2d 
```
To use the newer version, run `build.sh` without any options.  Copy the libraries into your WatchOS project that worked with the older OpenSSL version and see if that works.

**Comment by sunilsingh28011** [comment]
@jasonacox  Thanks for your reply. I want to update the version but I am new to do this So can you suggest me the step to step guidance, it will be appreciated more? Thanks for your help.

**Comment by jasonacox** [comment]
What is the WatchOS project you are working on?  Is it on GitHub? 

If you just want to know how to build the latest version, do this from your command line:

```bash
git clone https://github.com/jasonacox/Build-OpenSSL-cURL.git
cd Build-OpenSSL-cURL
./build.sh
```

Once it is complete, you will find the libraries built in the ./archive folder.  Alternatively, you can just use the libraries I recently built by downloading them from here: [https://github.com/jasonacox/Build-OpenSSL-cURL/tree/master/examples/iOS%20Test%20App/libs](https://github.com/jasonacox/Build-OpenSSL-cURL/tree/master/examples/iOS%20Test%20App/libs)

Install those libraries into your Xcode project.

**Comment by jasonacox** [comment]
I would create a backup of the old library, delete it and then install the new version.
