### ISSUE TITLE
Pre-built binaries for sample iOs app should not be included on source repo

### ISSUE THREAD

**Issue by spikegee** [jasonacox/Build-OpenSSL-cURL#41]
500 MiB downloaded on first checkout, that's a bit tough when one thinks it's downloading build scripts

**Comment by jasonacox** [comment]
Thanks @spikegee, excellent point. Most of the size was also tied up in old branches and binary histories. I have corrected that and it is now at 877KiB.  By the way, removing git history is a real pain... but worth it. :-)

```
Cloning into 'Build-OpenSSL-cURL'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 440 (delta 51), reused 82 (delta 40), pack-reused 297
Receiving objects: 100% (440/440), 877.85 KiB | 693.00 KiB/s, done.
Resolving deltas: 100% (196/196), done.
```

**Comment by spikegee** [comment]
A few hundred kiB only, nice job!
