### ISSUE TITLE
Curl wasn't built

### ISSUE THREAD

**Issue by Vasiliy-Krevega** [jasonacox/Build-OpenSSL-cURL#5]
Hey Jason,
So happy I've found your repo. Excellent work! 
The only issue is the build.sh fails to create curl libraries.
Here is a log I've got:

`Building OpenSSL
Cleaning up
Using openssl-1.0.1s.tar.gz
Unpacking openssl
Building Mac libraries
Building openssl-1.0.1s for x86_64
Copying headers
Building iOS libraries
Building openssl-1.0.1s for iPhoneOS  armv7
Building openssl-1.0.1s for iPhoneOS  armv7s
Building openssl-1.0.1s for iPhoneOS  arm64
Building openssl-1.0.1s for iPhoneSimulator  x86_64
Building openssl-1.0.1s for iPhoneSimulator  i386
Building tvOS libraries
Building openssl-1.0.1s for AppleTVOS  arm64
Building openssl-1.0.1s for AppleTVSimulator  x86_64
Cleaning up
Done
Building nghttp2 for HTTP2 support
Cleaning up
Using nghttp2-1.9.2.tar.gz
Unpacking nghttp2
Building Mac libraries
Building nghttp2-1.9.2 for x86_64
Building iOS libraries (bitcode)
Building nghttp2-1.9.2 for iPhoneOS  armv7
Building nghttp2-1.9.2 for iPhoneOS  armv7s
Building nghttp2-1.9.2 for iPhoneOS  arm64
Building nghttp2-1.9.2 for iPhoneSimulator  x86_64
Building nghttp2-1.9.2 for iPhoneSimulator  i386
Building tvOS libraries
Building nghttp2-1.9.2 for AppleTVOS  arm64
Building nghttp2-1.9.2 for AppleTVSimulator  x86_64
Cleaning up
Done

Building Curl
Building with HTTP2 Support (nghttp2)
Cleaning up
Using curl-7.48.0.tar.gz
Unpacking curl
Building Mac libraries
Building curl-7.48.0 for x86_64

Libraries...

opensll
Architectures in the fat file: openssl/Mac/lib/libcrypto.a are: x86_64 
Architectures in the fat file: openssl/Mac/lib/libssl.a are: x86_64 
Architectures in the fat file: openssl/iOS/lib/libcrypto.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: openssl/iOS/lib/libssl.a are: armv7 i386 x86_64 arm64 
Architectures in the fat file: openssl/tvOS/lib/libcrypto.a are: x86_64 arm64 
Architectures in the fat file: openssl/tvOS/lib/libssl.a are: x86_64 arm64 

nghttp2 (rename to libnghttp2.a)
Architectures in the fat file: nghttp2/lib/libnghttp2_Mac.a are: x86_64 
Architectures in the fat file: nghttp2/lib/libnghttp2_iOS.a are: armv7 armv7s i386 x86_64 arm64 
Architectures in the fat file: nghttp2/lib/libnghttp2_tvOS.a are: x86_64 arm64 

libcurl (rename to libcurl.a)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: curl/lib/*.a (No such file or directory)`

Thank you for your work,
Cheers,
Vasiliy Krevega

**Comment by Vasiliy-Krevega** [comment]
UPD: The scripts work perfectly. I had XCode command line tools being not installed. Installing them did solve the issue.
Thank you, Jason, once again! And sorry for making this noise here.

**Comment by bhatti-waqas** [comment]
I have Xcode Command line tools installed But I am facing the issue you mentioned above.

**Comment by jasonacox** [comment]
Look in /tmp and see if you have a curl*.log file.  Look at that to see what broke the build:

tail /tmp/curl*.log
