### ISSUE TITLE
Lib not found

### ISSUE THREAD

**Issue by lah64** [jasonacox/Build-OpenSSL-cURL#54]
When I add all 4 static libraries to the project, I start having problems, because XCode can't find these libraries for arm64, what could be the problem?

```
openssl/Mac/lib/libcrypto.a are:     x86_64 -OK arm64 - Lib not found (XCode)
openssl/Mac/lib/libssl.a are:           x86_64 -OK arm64 - Lib not found (XCode)
nghttp2/lib/libnghttp2_Mac.a are: x86_64 -OK arm64 - Lib not found (XCode)
curl/lib/libcurl_Mac.a are:               x86_64 -OK arm64 - OK
```

```
Version: 11.2.3 M1    - Problem
Version: 11.2.2 Intel  - OK
```

Steps:
1. any Mac on M1
2. Add: libcrypto.a _OR_ libnghttp2.a _OR_ libssl.a to project
3. Compile arm64
4. Get Output

**Comment by jasonacox** [comment]
Can you check that the static libraries have all of the architectures built?  It should look something like this:

```
$ file archive/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0/lib/MacOS/libcurl.a 

archive/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0/lib/MacOS/libcurl.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archive random library] [arm64]
archive/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0/lib/MacOS/libcurl.a (for architecture x86_64):	current ar archive random library
archive/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0/lib/MacOS/libcurl.a (for architecture arm64):	current ar archive random library
```

Also, for multiple target builds, another option is to use the _xcframework_ folder and copy those into your Xcode project.
The xcframework files are located in the `archive` folder:

```bash
$ ls -l archive/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0/xcframework      

 libcrypto.xcframework/
 libcurl.xcframework/
 libnghttp2.xcframework/
 libssl.xcframework/
```

**Comment by SKyzZz** [comment]
![Screenshot 2021-03-24 at 17 45 30](https://user-images.githubusercontent.com/3581307/112330170-dc29b200-8cc8-11eb-8e3b-f5678b5d7fc4.png)

**Comment by jasonacox** [comment]
Are you able to use xcframework to compile your project on the M1?

**Comment by SKyzZz** [comment]
Unfortunately not, alas. But I have identified the problem, most likely it is a problem with the libraries here because I took this and these libraries have been compiled successfully both the project. But I can compile + libnghttp2_Mac.a..

https://github.com/carsenk/openssl10-darwin-arm (libcrypto.a + libssl.a)

**Comment by jasonacox** [comment]
That's interesting.  I'm not able to duplicate your problem.  You can try:

1) Building without http2 (though I assume you are wanting http2):  `./build.sh -d`

2) Try to use the libraries I made:  [libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0.tgz](https://github.com/jasonacox/Build-OpenSSL-cURL/releases/download/v7.74.0/libcurl-7.74.0-openssl-1.1.1i-nghttp2-1.42.0.tgz)

**Comment by jasonacox** [comment]
Closing with the new update - please open if it is still an issue.
