### ISSUE TITLE
Silent build failure if missing pkg-config

### ISSUE THREAD

**Issue by tternes** [jasonacox/Build-OpenSSL-cURL#6]
First - thanks so much for getting these scripts together. Is there a tip jar somewhere?

I was experiencing a silent build failure during the libcurl portion of the script. Removing the logging redirect pointed me to:
 
`configure: error: --with-nghttp2 was specified but could not find libnghttp2 pig-config file`

After digging into the configure script a bit, it turned out that I didn't have `pkg-config` installed. `brew install pkgconfig` took care of the problem. Might be worth a sanity check pre-build.

**Comment by jasonacox** [comment]
Thanks Thaddeus!  I can add a check for `pkg-config` and alert or prompt to install.  I'll add that to my backlog unless you want to try it and submit a PR. :)

Thanks for the note!

**Comment by jasonacox** [comment]
I have updated the nghttp2 build script to check for pkg-config and attempt to install it if it is not already installed. Script is now building without errors.
