### ISSUE TITLE
能否升级一下OPENSSL3.1.1,因为我在使用build.h编译的时候发生了很多错误

### ISSUE THREAD

**Issue by xygkevin** [jasonacox/Build-OpenSSL-cURL#65]

**Comment by jasonacox** [comment]
> Can you upgrade OPENSSL3.1.1, because I have a lot of errors when compiling with build.h

Hi @xygkevin - thank you for your note and request.

The goal of this project is to support the latest Long Term Support (LTS) versions, not the latest development versions.  The latest builds change too fast to keep up.

FYI:
* OpenSSL 3.0.x is the current LTS version and is supported until 7th September 2026. 
* OpenSSL 3.1.x is latest dev version and support for that branch ends on 14th March 2025 
 (see [details here](https://www.openssl.org/source/)).

**Comment by xygkevin** [comment]
Thanks
