### ISSUE TITLE
Release lib error on my m1 imac

### ISSUE THREAD

**Issue by iPermanent** [jasonacox/Build-OpenSSL-cURL#69]
I download the release package and then drag it to my xcode directly, it's cocoa app, then show these errors below, I think some --disable-ldap and --disable --ldaps should add before the build action.

Undefined symbols for architecture arm64:
  "_ber_free", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_inflate", referenced from:
      _inflate_stream in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
  "_inflateEnd", referenced from:
      _inflate_stream in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
      _exit_zlib in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
  "_inflateInit2_", referenced from:
      _inflate_stream in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
      _gzip_init_writer in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
      _gzip_init_writer in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
  "_inflateInit_", referenced from:
      _deflate_init_writer in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
  "_ldap_err2string", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_first_attribute", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_first_entry", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_free_urldesc", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_get_dn", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_get_values_len", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_init", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_memfree", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_msgfree", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_next_attribute", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_next_entry", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_search_s", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_set_option", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_simple_bind_s", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_unbind_s", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_url_parse", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_ldap_value_free_len", referenced from:
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
      _ldap_do in libcurl.a[arm64][79](libcurl_la-ldap.o)
  "_zlibVersion", referenced from:
      _gzip_init_writer in libcurl.a[arm64][18](libcurl_la-content_encoding.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jasonacox** [comment]
Hi @iPermanent which package did you use?  I should flag that.  I'll upload a new release soon.

**Comment by jasonacox** [comment]
Try latest: https://github.com/jasonacox/Build-OpenSSL-cURL/releases/tag/v8.6.0

I assume you are importing the *xcframework* folders into your project in Xcode?

**Comment by iPermanent** [comment]
Thanks very much. I just build it myself by modify your shell and resolve it, with —disable-ldap and —disable-zlib.

**Comment by jasonacox** [comment]
Thanks Henry!  One thought, I seem to recall that without zlib you might run into issue with `Content-Encoding: gzip` content. If that is out of scope for your project you are fine. Otherwise you can add the zlib library in to your Xcode project.

<img width="571" alt="image" src="https://github.com/jasonacox/Build-OpenSSL-cURL/assets/836718/0d2e9812-14a8-4120-bee4-e6f5f93959e6">
